### ISSUE TITLE
Cyborg R.A.T.3 unsupported operand

### ISSUE THREAD

**Issue by krysoft** [MayeulC/Saitek#20]
Hi guys,

I have an issue with Saitek Cyborg R.A.T.3, when I run ratctl with sudo then I got TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'. VID and PID matching with R.A.T.3. Anybody have same experience or can knows whats going on?

Thanks for answers

**Comment by MayeulC** [comment]
Can you paste the whole log? Which line this happens? What are your VID and PID?

**Comment by krysoft** [comment]
This is complete output from the ratctl.py:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Found one device: {'vid': 1699, 'pid': 3276, 'name': 'Cyborg R.A.T.3'}
Traceback (most recent call last):
  File "./ratctl.py", line 402, in <module>
    main()
  File "./ratctl.py", line 392, in main
    w = MainWindow()
  File "./ratctl.py", line 378, in __init__
    self.data = Data(self.pbar, self.tabs, self.dpi, self.com)
  File "./ratctl.py", line 227, in __init__
    self.pool()
  File "./ratctl.py", line 230, in pool
    self.dpiMode = self.com.getDpiMode()
  File "./ratctl.py", line 152, in getDpiMode
    return mode[0] / 16
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

lsusb:

Bus 002 Device 005: ID 06a3:0ccc Saitek PLC Cyborg R.A.T.3 Mouse

Thanks for help I appreciate it!
